import type { Project } from "@/types/index";

export const PROJECTS: Project[] = [
  {
    num: "01",
    tag: "Featured",
    title: "Aurea",
    company: "Group Project",
    desc: "Full-stack jewellery e-commerce application built from the ground up as a group project, spanning design through to deployment. Ran user interviews, card sorting for navigation/footer structure, keyword analysis, storyboarding, speed dating techniques, and competitor analysis, then prototyped in Figma before building out the React/Node stack with product browsing, wishlists, and account features.",
    stack: ["React", "Node.js", "Nodemon", "MongoDB", "Axios", "Figma", "GitHub"],
    link: "https://github.com/AliceHeeyeon/Aurea",
    featured: true,
    image: "/images/projects/aurea.jpg",
  },
  {
    num: "02",
    tag: null,
    title: "Series Landing Page Redesign",
    company: "Aftershock PC Australia",
    desc: "Redesigned Aftershock's Series Landing Pages to improve conversion rates. Implemented a new design system, improved accessibility, and optimized for performance. Resulted in a 15% increase in conversions and a 20% decrease in bounce rate.",
    stack: ["Figma", "Remix", "Shopify/Hydrogen", "CRO"],
    link: "https://aftershockpc.com.au/series/zeal-mini-rgb",
    featured: false,
  },
  {
    num: "03",
    tag: null,
    title: "Team Performance Dashboard",
    company: "Aftershock PC Australia",
    desc: "Internal KPI dashboard consolidating Aircall, Front, and ClickUp data into a unified tool. Built with role-based access, per-member drill-downs, CSV upload infrastructure, Recharts trend visualisations, and an AI-powered insights layer via the Claude API. Replaced manual spreadsheet reporting entirely.",
    stack: [
      "Next.js",
      "Supabase",
      "Recharts",
      "Claude API",
      "Tailwind",
      "Vercel",
    ],
    link: null,
    featured: false,
  },
  {
    num: "04",
    tag: null,
    title: "LovelySmiles.co",
    company: "Freelance",
    desc: "Built and maintained the WordPress website for a Wellington beauty clinic group. Migrated from GoDaddy to AWS Lightsail to cut costs and improve load times. CMS setup, SEO optimisation, and ongoing content management.",
    stack: ["WordPress", "AWS Lightsail", "SEO", "CMS"],
    link: "https://lovelysmiles.co",
    featured: false,
  },
  {
    num: "05",
    tag: null,
    title: "Series Landing Page A/B Tests",
    company: "Aftershock PC Australia",
    desc: "Architected A/B testing framework for Aftershock's Series Landing Pages using Inteligems. Solved prior attribution issues caused by Hydrogen/React async rendering, establishing clean per-SLP tracking and purchase attribution on a headless Shopify stack.",
    stack: ["Shopify/Hydrogen", "Remix", "Inteligems", "CRO"],
    link: null,
    featured: false,
  },
  {
    num: "06",
    tag: null,
    title: "FiveM Server Scripts",
    company: "Infinity Gaming",
    desc: "Custom Lua scripts for a FiveM roleplay server: a weight-based movement effects system using OX-Inventory and state bags, and IG_EMS_DIAG — a full medical diagnostic NUI with interactive body region targeting and treatment integration.",
    stack: ["Lua", "FiveM", "OX-Inventory", "NUI/HTML"],
    link: "https://github.com/Ntoni596",
    featured: false,
  },
  {
    num: "07",
    tag: null,
    title: "Homepage Redesign Proposals",
    company: "Aftershock PC Australia",
    desc: "Figma design proposals for a homepage and product page refresh, covering the hero and 'built to perform' section, product carousel, custom-build CTA flow, and an RTX 5060 product page layout. Presented as mockups for stakeholder review.",
    stack: ["Figma", "UI Design", "Prototyping"],
    link: null,
    featured: false,
    image: "/images/projects/aftershock-redesign-ready-to-go.jpg",
    gallery: [
      "/images/projects/aftershock-redesign-ready-to-go.jpg",
      "/images/projects/aftershock-redesign-start-here.jpg",
      "/images/projects/aftershock-redesign-build-your-way.jpg",
      "/images/projects/aftershock-rts-proposal.jpg",
    ],
  },
];
